### ISSUE TITLE
Epic: Spring Framework — Security Hardening & Compliance

### ISSUE THREAD

**Issue by chrisrooney-max** [chrisrooney-max/legacy-migration#22]
# Epic: Spring Framework — Security Hardening & Compliance

## Overview
Address the security surface areas inherent in the Spring Framework codebase: SpEL injection risks, XML/XStream marshaller CVEs, multipart upload vulnerabilities, and dependency hygiene. This epic does not implement authentication/authorisation (Spring Security domain) but ensures the framework infrastructure does not introduce attack vectors.

## Scope
- Audit all ExpressionParser / EvaluationContext usage to identify paths where user-controlled input reaches SpEL evaluation; enforce use of SimpleEvaluationContext for untrusted input
- Remove or feature-flag XStreamMarshaller in spring-oxm behind an explicit opt-in; update dependency to a CVE-free version or replace with JAXB-only default
- Deprecate and remove CommonsMultipartResolver (Commons FileUpload) in favour of StandardServletMultipartResolver; document migration path
- Configure StaxUtils to disable external entity (XXE) processing on all XMLInputFactory / DocumentBuilderFactory instances; verify no instances were missed
- Validate that RuntimeHints does not expose sensitive class reflection paths in native image configuration
- Sign all release JARs with the Spring GPG key as part of the release pipeline; verify checksum publication to Maven Central
- Not in scope: Spring Security authentication/authorisation; end-user application security

## Acceptance Criteria
- [ ] A test confirms that passing a malicious SpEL expression to a SimpleEvaluationContext does not allow class loading or system command execution
- [ ] XStreamMarshaller is not on the default classpath without explicit opt-in; a deprecation warning is emitted when it is used
- [ ] CommonsMultipartResolver is annotated deprecated and the migration guide links to StandardServletMultipartResolver
- [ ] StaxUtils.createDefensiveInputFactory() is used in every XML-reading code path; a grep audit confirms no unguarded XMLInputFactory.newInstance() calls exist
- [ ] Release pipeline verifies GPG signature of all published JARs before closing Sonatype staging repository
- [ ] Dependency audit (OWASP Dependency-Check or equivalent) runs in CI and fails the build on CVSS >= 9.0 vulnerabilities in shipped dependencies

## Dependencies
- Epic: Spring Framework — Project Setup & Build Infrastructure

## Reference
- v3/security/index.md
- v3/change-risk/index.md — XStream and SpEL risks
- SECURITY.md — vulnerability reporting policy
